### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by jsedoc** [ChengyueGongR/FrequencyAgnostic#4]
Hi, 

Great work! 

I was wondering if it would be possible to share your model parameters.

Thanks!

**Comment by ChengyueGongR** [comment]
Sure. I can upload the model parameters. Please wait for some days, I cannot reproduce the results after I use pytorch0.4. Let me first fix this problem.

I will first upload the model on pytorch0.2 within a week if possible. Let me first reproduce it.

update 3.16:
1) I have uploaded the pre-trained model and the code on MoS-AWD-LSTM-PTB. 
2) The result of WT2 will need some time to reproduce.

update 3.20:
1) I have uploaded the pre-trained model and the code on AWD-LSTM-PTB.
