### ISSUE TITLE
Dynamic Eval not working

### ISSUE THREAD

**Issue by jandonov** [ChengyueGongR/FrequencyAgnostic#6]
Hi,

I am trying to reproduce the awd-lstm (without MOS) results. 
I used the following commands:

`pytho3 main.py --nonmono 5 --batch_size 20 --data ../../../data/penn --dropouth 0.25 --dropouti 0.3 --dropout 0.4 --alpha 2 --beta 1 --seed 141 --epoch 2000 --save ./trained_model/ptb.pt
`

and then

`python pointer.py --data ../../../data/penn --save trained_model/ptb.pt --lambdasm 0.08 --theta 1.4 --window 500 --bptt 5000
`

Both commands finished with no issues using Python 3.7 and PyTorch 0.4, however when I tried running dynamic eval using:

`python dynamiceval.py --data ../../../data/penn --model trained_model/ptb.pt --lamb 0.075 --gpu 2`

I am receiving the following error:

> Traceback (most recent call last):
  File "dynamiceval.py", line 228, in <module>
    gradstat()
  File "dynamiceval.py", line 107, in gradstat
    loss = nn.functional.nll_loss(log_prob.view(-1, log_prob.size(2)), targets)
RuntimeError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Any hints?

**Comment by ChengyueGongR** [comment]
See the dynamiceval.py file in https://github.com/zihangdai/mos for how to solve it.
The reason should be that I do not change the version to PyTorch 0.4 for the dynamic eval, for AWD-LSTM without MoS.
Maybe I will update the file later.
